name: Release

on:
  release:
    types: [ "published" ]

permissions:
  contents: write

env:
  BUILD_TYPE: Release
  LANG: 'en_US.UTF-8'

jobs:
  release:
    name: Release for ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - machine: 'macos-13'
            os: 'darwin'
            arch: 'x86_64'
            name: macOS x86_64
          - machine: 'macos-14'
            os: 'darwin'
            arch: 'arm64'
            name: macOS ARM64
          - machine: 'ubuntu-24.04-arm'
            os: 'linux'
            arch: 'aarch64'
            name: Linux ARM64
          - machine: 'ubuntu-24.04'
            os: 'linux'
            arch: 'x86_64'
            name: Linux x86_64

    runs-on: ${{ matrix.machine }}
    env:
      ARTIFACT_NAME: arm-webos-linux-gnueabi_sdk-buildroot_${{matrix.os}}-${{matrix.arch}}.tar.bz2

    steps:
      - uses: actions/checkout@v4

      - id: build-toolchain
        name: Build Toolchain
        uses: './.github/actions/build-toolchain'
        with:
          machine: ${{ matrix.machine }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

      - name: Make Tarball
        run: |
          cmake -E tar cjvf ${ARTIFACT_NAME} arm-webos-linux-gnueabi_sdk-buildroot
        working-directory: ${{steps.build-toolchain.outputs.dist}}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.event.release.tag_name }}
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: ${{github.workspace}}/build/dist/${{env.ARTIFACT_NAME}}
